[package]
name = "sm2-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ['dylib']

[dependencies]
blake3 = "1.4.1"
jni = "0.21.1"
libsm = "0.5.1"
rustc-serialize = "0.3.24"
